{{- if .Values.openshift.active }}
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "{{ template "harbor.jobservice" . }}"
  labels:
    build: "{{ template "harbor.jobservice" . }}"
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'harbor-jobservice:{{ .Values.jobservice.image.tag }}'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
  postCommit: {}
  source:
    type: Dockerfile
    dockerfile: |-
      FROM goharbor/harbor-jobservice:{{ .Values.jobservice.image.tag }}
      RUN chmod o+rwx /harbor/ && \
          chmod o+rwx /harbor/*.sh && \
          chmod o+rwx /etc/pki/tls/certs/ca-bundle.crt
  triggers:
    - type: ImageChange
    - type: ConfigChange
  runPolicy: Serial
status: {}
{{- end -}}
