{{- $scandataExports := .Values.persistence.persistentVolumeClaim.jobservice.scanDataExports -}}
{{- if and .Values.persistence.enabled (not $scandataExports.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "harbor.jobserviceScandata" . }}
  annotations:
  {{- range $key, $value := $scandataExports.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: jobservice
spec:
  accessModes: 
    - {{ $scandataExports.accessMode }}
  resources:
    requests:
      storage: {{ $scandataExports.size }}
  {{- if $scandataExports.storageClass }}
    {{- if eq "-" $scandataExports.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ $scandataExports.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
