{{- $secret := include "harbor.jobservice" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Release.IsUpgrade }}
    {{- $prevSecret := (lookup "v1" "Secret" .Release.Namespace $secret) }}
    {{- if .Values.jobservice.secret }}
  JOBSERVICE_SECRET: {{ .Values.jobservice.secret | b64enc | quote }}
    {{- else if $prevSecret }}
  JOBSERVICE_SECRET: {{ $prevSecret.data.JOBSERVICE_SECRET }}
    {{- else }}
  JOBSERVICE_SECRET: {{ randAlphaNum 16 | b64enc | quote }}
    {{- end }}
  {{- else }}
  JOBSERVICE_SECRET: {{ .Values.jobservice.secret | default (randAlphaNum 16) | b64enc | quote }}
  {{- end }}
  REGISTRY_CREDENTIAL_PASSWORD: {{ .Values.registry.credentials.password | b64enc | quote }}
