{{- if .Values.jobservice.podDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ template "harbor.jobservice" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: jobservice
spec:
  selector:
    matchLabels:
{{ include "harbor.matchLabels" . | indent 6 }}
      component: jobservice
{{- if .Values.jobservice.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: "{{ .Values.jobservice.podDisruptionBudget.maxUnavailable }}"
{{- end }}
{{- if .Values.jobservice.podDisruptionBudget.minAvailable }}
  minAvailable: "{{ .Values.jobservice.podDisruptionBudget.minAvailable }}"
{{- end }}
{{- end }}
