apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.jobservice" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  {{- ( include "harbor.jobservice.secret" . ) | indent 2 -}}
  
