apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.portal" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: portal
