{{- if and .Values.portal.podDisruptionBudget.enabled (gt (int .Values.portal.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "harbor.portal" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  {{- if .Values.portal.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.portal.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.portal.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.portal.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: portal
{{- end }}