{{- if eq .Values.redis.type "internal" -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.redis" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  REDIS_PASSWORD: {{ template "harbor.redis.encryptedPassword" . }}
{{- end -}}
