{{ if .Values.jobConfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "harbor.jobConfig" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  config.json: {{ .Values.jobConfig.settings | toJson | b64enc | quote }}
{{ end }}
