{{ if .Values.notary.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "harbor.notary-server" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: notary-server
spec:
{{- if  (eq .Values.expose.ingress.controller "gce") }}
  type: NodePort
{{- end }}
  ports:
  - name: http
    port: 4443
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: notary-server

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "harbor.notary-signer" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: notary-signer
spec:
  ports:
  - port: 7899
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: notary-signer
{{ end }}