{{- if and .Values.notary.enabled }}
{{- $secret := include "harbor.notary-server" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: notary
type: Opaque
data:
  {{- if not .Values.notary.secretName }}
  {{- $ca := genCA "harbor-notary-ca" 365 }}
  {{- $cert := genSignedCert (include "harbor.notary-signer" .) nil nil 365 $ca }}
  {{- $certCtx := (merge (dict "ca" $ca "cert" $cert "secret" $secret "rotateCert" .Values.notary.rotateCert ) .) }}
{{ include "harbor.getGenCertOrLoadFromSecret" $certCtx | indent 2 }}
  {{- end }}
  server.json: {{ tpl (.Files.Get "conf/notary-server.json") . | b64enc }}
  signer.json: {{ tpl (.Files.Get "conf/notary-signer.json") . | b64enc }}
{{- end }}
