{{ if .Values.notary.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "harbor.notary-server" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
{{- if not .Values.notary.secretName }}
  {{ $ca := genCA "harbor-notary-ca" 365 }}
  {{ $cert := genSignedCert (include "harbor.notary-signer" .) nil nil 365 $ca }}
  notary-signer-ca.crt: {{ $ca.Cert | b64enc }}
  notary-signer.crt: {{ $cert.Cert | b64enc }}
  notary-signer.key: {{ $cert.Key | b64enc }}
{{- end }}
  server-config.postgres.json: {{ tpl (.Files.Get "conf/server-config.postgres.json") . | b64enc }}
  signer-config.postgres.json: {{ tpl (.Files.Get "conf/signer-config.postgres.json") . | b64enc }}
{{- end }}