{{- if .Values.custom.oidc.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-oidc
  namespace: {{ .Release.Namespace }}
data:
  configureOidc.sh: |
    #!/bin/sh
    set -e
    curl -u "${HARBOR_ADMIN_USERNAME}:${HARBOR_ADMIN_PASSWORD}" \
    -X PUT \
    -H "Content-Type: application/json" \
    -ki {{ .Values.expose.ingress.hosts.core }}/api/v2.0/configurations \
    -d "{ \"auth_mode\":\"$AUTH_MODE\",\"oidc_name\":\"$OIDC_NAME\",\"oidc_endpoint\":\"$OIDC_ENDPOINT\",\"oidc_client_id\":\"$OIDC_CLIENT_ID\",\"oidc_client_secret\":\"$OIDC_CLIENT_SECRET\",\"oidc_scope\":\"$OIDC_SCOPE\",\"oidc_groups_claim\":\"$OIDC_GROUPS_CLAIM\"}"
{{- end }}