apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "harbor.core" . }}-app
  labels:
{{ include "harbor.labels" . | indent 4 }}
data:
  app.conf: |+
    appname = Harbor
    runmode = prod
    enablegzip = true

    [prod]
    httpport = 8080