{{- if or (eq .Values.database.external.sslmode "require") (eq .Values.database.external.sslmode "verify-ca") (eq .Values.database.external.sslmode "verify-full") }}
{{- if not .Values.database.external.secretNameCertsKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: db-cert-key
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  harbor-ca-cert.pem: {{ .Values.database.external.certskeys.rootCert }}
  harbor-client-cert.pem: {{ .Values.database.external.certskeys.clientCert }}
  harbor-client-key.pem: {{ .Values.database.external.certskeys.clientKey }}
{{- end }}
{{- end }}
