{{- if and .Values.internalTLS.enabled (eq .Values.internalTLS.certSource "auto") }}
{{- $ca := genCA "harbor-internal-ca" .Values.internalTLS.certValidity.caCert }}
{{- $coreCN := (include "harbor.core" .) }}
{{- $coreCrt := genSignedCert $coreCN (list "127.0.0.1") (list "localhost" $coreCN) .Values.internalTLS.certValidity.clientCert $ca }}
{{- $jsCN := (include "harbor.jobservice" .) }}
{{- $jsCrt := genSignedCert $jsCN nil (list $jsCN) .Values.internalTLS.certValidity.clientCert $ca }}
{{- $regCN := (include "harbor.registry" .) }}
{{- $regCrt := genSignedCert $regCN nil (list $regCN) .Values.internalTLS.certValidity.clientCert $ca }}
{{- $portalCN := (include "harbor.portal" .) }}
{{- $portalCrt := genSignedCert $portalCN nil (list $portalCN) .Values.internalTLS.certValidity.clientCert $ca }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.internalTLS.core.secretName" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca.Cert | b64enc | quote }}
  tls.crt: {{ $coreCrt.Cert | b64enc | quote }}
  tls.key: {{ $coreCrt.Key | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.internalTLS.jobservice.secretName" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca.Cert | b64enc | quote }}
  tls.crt: {{ $jsCrt.Cert | b64enc | quote }}
  tls.key: {{ $jsCrt.Key | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.internalTLS.registry.secretName" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca.Cert | b64enc | quote }}
  tls.crt: {{ $regCrt.Cert | b64enc | quote }}
  tls.key: {{ $regCrt.Key | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.internalTLS.portal.secretName" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca.Cert | b64enc | quote }}
  tls.crt: {{ $portalCrt.Cert | b64enc | quote }}
  tls.key: {{ $portalCrt.Key | b64enc | quote }}

{{- if .Values.chartmuseum.enabled }}
---
{{- $chartCN := (include "harbor.chartmuseum" .) }}
{{- $chartCrt := genSignedCert $chartCN nil (list $chartCN) .Values.internalTLS.certValidity.clientCert $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.internalTLS.chartmuseum.secretName" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca.Cert | b64enc | quote }}
  tls.crt: {{ $chartCrt.Cert | b64enc | quote }}
  tls.key: {{ $chartCrt.Key | b64enc | quote }}
{{- end }}

{{- if and .Values.trivy.enabled}}
---
{{- $trivyCN := (include "harbor.trivy" .) }}
{{- $trivyCrt := genSignedCert $trivyCN nil (list $trivyCN) .Values.internalTLS.certValidity.clientCert $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.internalTLS.trivy.secretName" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca.Cert | b64enc | quote }}
  tls.crt: {{ $trivyCrt.Cert | b64enc | quote }}
  tls.key: {{ $trivyCrt.Key | b64enc | quote }}
{{- end }}

{{- end }}