{{- if and .Values.internalTLS.enabled (eq .Values.internalTLS.certSource "auto") }}
{{- $ca := genCA "harbor-internal-ca" 365 }}
{{- $coreCN := (include "harbor.core" .) }}
{{- $coreCrt := genSignedCert $coreCN (list "127.0.0.1") (list "localhost" $coreCN) 365 $ca }}
{{- $jsCN := (include "harbor.jobservice" .) }}
{{- $jsCrt := genSignedCert $jsCN nil (list $jsCN) 365 $ca }}
{{- $regCN := (include "harbor.registry" .) }}
{{- $regCrt := genSignedCert $regCN nil (list $regCN) 365 $ca }}
{{- $portalCN := (include "harbor.portal" .) }}
{{- $portalCrt := genSignedCert $portalCN nil (list $portalCN) 365 $ca }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.internalTLS.core.secretName" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  {{- $certCtx := (merge (dict "ca" $ca "cert" $coreCrt "secret" (include "harbor.internalTLS.core.secretName" .) "rotateCert" .Values.internalTLS.rotateCert ) .) }}
{{ include "harbor.getGenCertOrLoadFromSecret" $certCtx | indent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.internalTLS.jobservice.secretName" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  {{- $certCtx := (merge (dict "ca" $ca "cert" $jsCrt "secret" (include "harbor.internalTLS.jobservice.secretName" .) "rotateCert" .Values.internalTLS.rotateCert ) .) }}
{{ include "harbor.getGenCertOrLoadFromSecret" $certCtx | indent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.internalTLS.registry.secretName" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  {{- $certCtx := (merge (dict "ca" $ca "cert" $regCrt "secret" (include "harbor.internalTLS.registry.secretName" .) "rotateCert" .Values.internalTLS.rotateCert ) .) }}
{{ include "harbor.getGenCertOrLoadFromSecret" $certCtx | indent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.internalTLS.portal.secretName" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  {{- $certCtx := (merge (dict "ca" $ca "cert" $portalCrt "secret" (include "harbor.internalTLS.portal.secretName" .) "rotateCert" .Values.internalTLS.rotateCert ) .) }}
{{ include "harbor.getGenCertOrLoadFromSecret" $certCtx | indent 2 }}

{{- if .Values.chartmuseum.enabled }}
---
{{- $chartCN := (include "harbor.chartmuseum" .) }}
{{- $chartCrt := genSignedCert $chartCN nil (list $chartCN) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.internalTLS.chartmuseum.secretName" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  {{- $certCtx := (merge (dict "ca" $ca "cert" $chartCrt "secret" (include "harbor.internalTLS.chartmuseum.secretName" .) "rotateCert" .Values.internalTLS.rotateCert ) .) }}
{{ include "harbor.getGenCertOrLoadFromSecret" $certCtx | indent 2 }}
{{- end }}

{{- if .Values.clair.enabled }}
---
{{- $clairCN := (include "harbor.clair" .) }}
{{- $clairCrt := genSignedCert $clairCN nil (list $clairCN) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.internalTLS.clair.secretName" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  {{- $certCtx := (merge (dict "ca" $ca "cert" $clairCrt "secret" (include "harbor.internalTLS.clair.secretName" .) "rotateCert" .Values.internalTLS.rotateCert ) .) }}
{{ include "harbor.getGenCertOrLoadFromSecret" $certCtx | indent 2 }}
{{- end }}

{{- if and .Values.trivy.enabled}}
---
{{- $trivyCN := (include "harbor.trivy" .) }}
{{- $trivyCrt := genSignedCert $trivyCN nil (list $trivyCN) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.internalTLS.trivy.secretName" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  {{- $certCtx := (merge (dict "ca" $ca "cert" $trivyCrt "secret" (include "harbor.internalTLS.trivy.secretName" .) "rotateCert" .Values.internalTLS.rotateCert ) .) }}
{{ include "harbor.getGenCertOrLoadFromSecret" $certCtx | indent 2 }}
{{- end }}

{{- end }}