{{- if .Values.registry.podDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ template "harbor.registry" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: registry
spec:
  selector:
    matchLabels:
{{ include "harbor.matchLabels" . | indent 6 }}
      component: registry
{{- if .Values.registry.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: "{{ .Values.registry.podDisruptionBudget.maxUnavailable }}"
{{- end }}
{{- if .Values.registry.podDisruptionBudget.minAvailable }}
  minAvailable: "{{ .Values.registry.podDisruptionBudget.minAvailable }}"
{{- end }}
{{- end }}
