apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.registry" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: registry
spec:
  ports:
    - name: registry
      port: 5000
    - name: controller
      port: 8080
  {{- if .Values.registry.exposeDebug }}
    - name: debug
      port: 5001
  {{- end }}
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: registry
