{{- if .Values.openshift.active }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: "{{ template "harbor.registry" . }}ctl"
spec:
  lookupPolicy:
    local: false
status: {}
{{- end -}}
