{{- if .Values.registry.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ template "harbor.registry" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: registry 
spec:
  {{- if .Values.registry.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.registry.podDisruptionBudget.maxUnavailable }}
  {{- else if .Values.registry.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.registry.podDisruptionBudget.minAvailable }}
  {{- end  }}
  selector:
    matchLabels:
{{ include "harbor.matchLabels" . | indent 6 }}
      component: registry
{{- end }}
