apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.registry" . }}"
  labels:
    component: registry
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
    - name: registry
      port: {{ template "harbor.registry.servicePort" . }}
    - name: controller
      port: {{ template "harbor.registryctl.servicePort" . }}
{{- if .Values.metrics.enabled}}
    - name: metrics
      port: {{ .Values.metrics.registry.port }}
{{- end }}
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: registry
