apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "harbor.registryCtl" . }}"
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
{{- if .Values.commonAnnotations }}
  annotations:
{{ toYaml .Values.commonAnnotations | indent 4 }}
{{- end }}
data:
  {{- template "harbor.traceEnvsForRegistryCtl" . }}
