{{- if .Values.clair.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "harbor.clair" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  config.yaml: {{ tpl (.Files.Get "conf/clair-config.yaml") . | b64enc }}
{{- end }}