{{ if .Values.clair.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "harbor.clair" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: clair
data:
  config.yaml: |
    clair:
      database:
        type: pgsql
        options:
          source: "{{ template "harbor.database.clair" . }}"
          # Number of elements kept in the cache
          # Values unlikely to change (e.g. namespaces) are cached in order to save prevent needless roundtrips to the database.
          cachesize: 16384

      api:
        # API server port
        port: 6060
        healthport: 6061

        # Deadline before an API request will respond with a 503
        timeout: 300s
      updater:
        interval: {{ .Values.clair.updatersInterval }}h
      
      healthaddr: "0.0.0.0:6061"

      notifier:
        attempts: 3
        renotifyinterval: 2h
        http:
          endpoint: "http://{{ template "harbor.core" . }}/service/notifications/clair"
{{ end }}
