{{- if .Values.trivy.opa.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "harbor.trivy" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  policy.rego: |
    {{ .Values.trivy.opa.policy | nindent 4 }}
{{- end }}
