apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.adminserver" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: adminserver
type: Opaque
data:
  secretKey: {{ .Values.secretKey | b64enc | quote }}
  HARBOR_ADMIN_PASSWORD: {{ .Values.harborAdminPassword | b64enc | quote }}
  POSTGRESQL_PASSWORD: {{ template "harbor.database.encryptedPassword" . }}
{{ if .Values.clair.enabled }}
  CLAIR_DB_PASSWORD: {{ template "harbor.database.encryptedPassword" . }}
{{ end }}
