apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "harbor.fullname" . }}-adminserver"
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: adminserver
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "harbor.matchLabels" . | indent 6 }}
      component: adminserver
  template:
    metadata:
      labels:
{{ include "harbor.labels" . | indent 8 }}
        component: adminserver
    spec:
      containers:
      - name: adminserver
        image: "{{ .Values.adminserver.image.repository }}:{{ .Values.adminserver.image.tag }}"
        imagePullPolicy: "{{ .Values.adminserver.image.pullPolicy }}"
        resources:
{{ toYaml .Values.adminserver.resources | indent 10 }}
        envFrom:
        - configMapRef:
            name: "{{ template "harbor.fullname" . }}-adminserver"
        - secretRef:
            name: "{{ template "harbor.fullname" . }}-adminserver"
        env:
          - name: PORT
            value: "8080"
          - name: JSON_CFG_STORE_PATH
            value: /etc/adminserver/config/config.json
          - name: KEY_PATH
            value: /etc/adminserver/key
          - name: UI_SECRET
            valueFrom:
              secretKeyRef:
                name: "{{ template "harbor.fullname" . }}-ui"
                key: secret
          - name: JOBSERVICE_SECRET
            valueFrom:
              secretKeyRef:
                name: "{{ template "harbor.fullname" . }}-jobservice"
                key: secret
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: adminserver-key
          mountPath: /etc/adminserver/key
          subPath: key
      volumes:
      - name: adminserver-key
        secret:
          secretName: "{{ template "harbor.fullname" . }}-adminserver"
          items:
          - key: secretKey
            path: key
    {{- with .Values.adminserver.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.adminserver.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.adminserver.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}