apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "harbor.adminserver" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: adminserver
spec:
  replicas: {{ .Values.adminserver.replicas }}
  selector:
    matchLabels:
{{ include "harbor.matchLabels" . | indent 6 }}
      component: adminserver
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/adminserver/adminserver-cm.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/adminserver/adminserver-secret.yaml") . | sha256sum }}
      labels:
{{ include "harbor.labels" . | indent 8 }}
        component: adminserver
    spec:
      containers:
      - name: adminserver
        image: "{{ .Values.adminserver.image.repository }}:{{ .Values.adminserver.image.tag }}"
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        livenessProbe:
          httpGet:
            path: /api/ping
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/ping
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 10
        resources:
{{ toYaml .Values.adminserver.resources | indent 10 }}
        envFrom:
        - configMapRef:
            name: "{{ template "harbor.adminserver" . }}"
        - secretRef:
            name: "{{ template "harbor.adminserver" . }}"
        env:
          - name: PORT
            value: "8080"
          - name: JSON_CFG_STORE_PATH
            value: /etc/adminserver/config/config.json
          - name: KEY_PATH
            value: /etc/adminserver/key
          - name: CORE_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ template "harbor.core" . }}
                key: secret
          - name: JOBSERVICE_SECRET
            valueFrom:
              secretKeyRef:
                name: "{{ template "harbor.jobservice" . }}"
                key: secret
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: adminserver-key
          mountPath: /etc/adminserver/key
          subPath: key
      volumes:
      - name: adminserver-key
        secret:
          secretName: "{{ template "harbor.adminserver" . }}"
          items:
          - key: secretKey
            path: key
    {{- with .Values.adminserver.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.adminserver.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.adminserver.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}