apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.fullname" . }}-adminserver"
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: adminserver
type: Opaque
data:
  secretKey: {{ .Values.secretKey | b64enc | quote }}
{{ if .Values.email.enabled }}
  EMAIL_PWD: {{ .Values.email.password | b64enc | quote }}
{{ end }}
{{ if eq .Values.auth.mode "ldap_auth" }}
  LDAP_SEARCH_PWD: {{ .Values.auth.ldap.searchPassword | b64enc | quote }}
{{ end }}
  HARBOR_ADMIN_PASSWORD: {{ .Values.harborAdminPassword | b64enc | quote }}
  POSTGRESQL_PASSWORD: {{ template "harbor.database.password" . }}
{{ if .Values.clair.enabled }}
  CLAIR_DB_PASSWORD: {{ template "harbor.database.password" . }}
{{ end }}
