{{- if eq (include "harbor.autoGenCertForIngress" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.ingress" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  {{- ( include "harbor.ingress.secret" . ) | indent 2 -}}
{{- end }}