{{- if eq (include "harbor.autoGenCertForIngress" .) "true" }}
  {{- $secret := include "harbor.ingress" . }}
  {{- $ca := genCA "harbor-ca" 365 }}
  {{- $cert := genSignedCert .Values.expose.ingress.hosts.core nil (list .Values.expose.ingress.hosts.core .Values.expose.ingress.hosts.notary) 365 $ca }}
  {{- $certCtx := (merge (dict "ca" $ca "cert" $cert "secret" $secret "rotateCert" .Values.expose.tls.auto.rotateCert ) .) }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $secret }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
{{ include "harbor.getGenCertOrLoadFromSecret" $certCtx | indent 2 }}
{{- end }}