apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.database" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
{{- $password := (include "harbor.database.password" .) }}
{{- $passwordCtx := (merge (dict "databasePassword" $password) .) }}
  POSTGRES_PASSWORD: {{ $password | b64enc | quote }}
  POSTGRES_URL_NOTARY_SERVER: {{ include "harbor.database.notaryServer" $passwordCtx | b64enc }}
  POSTGRES_URL_NOTARY_SIGNER: {{ include "harbor.database.notarySigner" $passwordCtx | b64enc }}
  POSTGRES_URL_CLAIR: {{ include "harbor.database.clair" $passwordCtx | b64enc }}
