{{- if .Values.openshift.active }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: "{{ .Values.database.internal.image.repository }}"
spec:
  lookupPolicy:
    local: false
status: {}
{{- end -}}
