{{- if eq .Values.database.type "internal" -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.database" . }}"
  namespace: {{ template "harbor.namespace" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ template "harbor.database.encryptedPassword" . }}
{{- end -}}
