{{- if eq (include "harbor.autoGenCertForNginx" .) "true" }}
  {{- $secret := include "harbor.nginx" . }}
  {{- $ca := genCA "harbor-ca" 365 }}
  {{- $cn := (required "The \"expose.tls.auto.commonName\" is required!" .Values.expose.tls.auto.commonName) }}
  {{- $certData := dict -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  {{- if regexMatch `^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$` $cn }}
    {{- $cert := genSignedCert $cn (list $cn) nil 365 $ca }}
    {{- $certCtx := (merge (dict "ca" $ca "cert" $cert "secret" $secret "rotateCert" .Values.expose.tls.auto.rotateCert ) .) }}
{{ include "harbor.getGenCertOrLoadFromSecret" $certCtx | indent 2 }}
  {{- else }}
    {{- $cert := genSignedCert $cn nil (list $cn) 365 $ca }}
    {{- $certCtx := (merge (dict "ca" $ca "cert" $cert "secret" $secret "rotateCert" .Values.expose.tls.auto.rotateCert ) .) }}
{{ include "harbor.getGenCertOrLoadFromSecret" $certCtx | indent 2 }}
  {{- end }}
{{- end }}