{{- if and .Values.metrics.enabled .Values.exporter.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "{{ template "harbor.exporter" . }}"
spec:
{{- if .Values.exporter.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.exporter.podDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.exporter.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.exporter.podDisruptionBudget.maxUnavailable }}
{{- end }}
  selector:
    matchLabels:
{{ include "harbor.matchLabels" . | indent 6 }}    
      component: exporter
{{- end }}
