{{- if and .Values.exporter.enabled .Values.exporter.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ template "harbor.exporter" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: exporter
spec:
  endpoints:
    - interval: {{ .Values.exporter.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.exporter.serviceMonitor.scrapeTimeout }}
      honorLabels: true
      port: http
      path: /metrics
      scheme: http
  jobLabel: exporter
  selector:
    matchLabels:
      component: exporter
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end -}}